trigger:
  branches:
    include:
      - "master"
      - "main"
      - "RELEASE/*"

resources:
  repositories:
    - repository: self
    - repository: devops
      name: devops
      type: git

extends:
  template: pipelines/dockerhub/sonar/microservices-gradle-sonar-dockerhub.yml@devops
