management:
  endpoints:
    web:
      exposure:
        include: health, info, restart
  endpoint:
    health:
      show-details: always
    restart:
      enabled: true
  server:
    port: 8081

server:
  port: 8080