management:
  endpoints:
    web:
      exposure:
        include: health, info, restart
  endpoint:
    health:
      show-details: always
    restart:
      enabled: true
  server:
    port: 8081

server:
  port: 8080

spring:
  data:
    mongodb:
      uri: "mongodb+srv://victor:0113@victorsoaresdb.aezzb.mongodb.net/myFirstDatabase?retryWrites=true&w=majority"